
-- ANIMAL_INS TABLE 기준으로
SELECT AINS.ANIMAL_ID, AINS.NAME
FROM  ANIMAL_INS AINS
LEFT JOIN ANIMAL_OUTS AOUTS ON AOUTS.ANIMAL_ID = AINS.ANIMAL_ID
WHERE AOUTS.DATETIME < AINS.DATETIME
ORDER BY AINS.DATETIME ASC


-- ANIMAL_OUTS TABLE 기준으로
SELECT AOUTS.ANIMAL_ID, AOUTS.NAME
FROM ANIMAL_OUTS AOUTS
LEFT JOIN ANIMAL_INS AINS ON AOUTS.ANIMAL_ID = AINS.ANIMAL_ID
WHERE AINS.DATETIME > AOUTS.DATETIME
ORDER BY AINS.DATETIME